### ISSUE TITLE
Fulltext search field missing / removed

### ISSUE THREAD

**Issue by tstoeber** [reneeb/otrs-MoveLogoutButton#1]
After installing this package, the fulltext search field (maybe other fields?) is missing / no longer visible. I think this is Frontend::ToolBarModule###10-Ticket::TicketSearchFulltext in OTRS. Similiar (identical) bug reported on OPAR.

**Comment by reneeb** [comment]
Fixed with latest version...

**Comment by reneeb** [comment]
commit that fixes this issue: https://github.com/reneeb/otrs-MoveLogoutButton/commit/c41d045032e2437289495594baae5604842b7ea0
